version: '3.7'

services: 
    app:
        build: 
            context: .
        ports: 
            - "8000:8000"
        volumes: 
            - static_data:vol/web
        environment: 
            - SECRET_KEY=django-insecure-l6=&d4p*ikxdgojt2%l9obqe_72o+x-hzvqz^u59^-ioghvv*m
            - DEBUG=0
            - ALLOWED_HOSTS=127.0.0.1,localhost
        depends_on: 
            - db

    db:
        image: postgres

    proxy:
        build: 
            context: ./proxy
        volumes: 
            - static_data:/vol/static
        ports: 
            - "8080:8080"

        depends_on: 
            - app

volumes: 
    static_data: